### ISSUE TITLE
Suggestion for markdown package

### ISSUE THREAD

**Issue by IdiosApps** [jpmvferreira/espanso-mega-pack#5]
https://github.com/jpmvferreira/espanso-mega-pack/blob/master/markdown-shortcuts/0.1.0/package.yml

First of all, great Espanso package! Good naming of markdown items too 👏 

I have a suggestion for alternative usage. I might struggle to remember the exact wording for each entry, so:
We could have multiple matches for `:md:`, so when we type that Espanso lets us select the relevant one from a UI popup window. It does mean when using this you need to know what kind of markdown you're looking for

```yaml
  - triggers: [":md:"]
    replace: "- [x] "
  - triggers: [":md:"]
    replace: |-
        <details>
        <summary></summary>
        $|$
        </details>
    force_clipboard: true
  - triggers: [":md:"]
    replace: |-
        ```$|$
        ```
    force_clipboard: true
```

I'm not sure exactly how it would look in the popup, but it's like a quick reference guide that means you don't need to do a web search.
If you think that sounds interesting, I could try it out and raise a PR to see what you think :)
