### ISSUE TITLE
Add comment replacement

### ISSUE THREAD

**Issue by IdiosApps** [jpmvferreira/espanso-mega-pack#6]
```yaml
  - triggers: ":comment:"
    replace: <!---
        `$|$`
-->
```

Something like this 
There might be other markdowns we can add. What do you think?
